modLoader="javafml"
loaderVersion="${forgeLoaderVersion}"
license="BSD-3-Clause"
issueTrackerURL="https://github.com/YaLTeR/MouseTweaks/issues"
clientSideOnly=true

[[mods]]
modId="mousetweaks"
version="${version}"
displayName="Mouse Tweaks"
displayURL="https://minecraft.curseforge.com/projects/mouse-tweaks"
logoFile="mousetweaks_logo.png"
credits="${modCredits}"
authors="Ivan Molodetskikh (YaLTeR)"
description="${modDescription}"
